apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neonvm-system
namePrefix: neonvm-
resources:
- namespace
- crd
- rbac
- webhook
- certmanager
- network
- device-plugin
patches:
- path: webhookcainjection_patch.yaml
