#!/bin/sh
# Read a secret directories into env-file format
#
# Input:
# /secrets/prefix1/file1
# /secrets/prefix2/file2
# /secrets/prefix2/file3
#
# $ secrets-to-env /secrets
# PREFIX1_FILE1=...
# PREFIX2_FILE1=...
# PREFIX2_FILE2=...

base_dir="$1"

for dir in "$base_dir"/*; do
    [ -d "$dir" ] || continue

    prefix=$(basename "$dir" | tr 'a-z-' 'A-Z_')

    for file in "$dir"/*; do
        [ -f "$file" ] || continue
        name=$(basename "$file" | tr 'a-z-' 'A-Z_')
        key="${prefix}_${name}"
        printf '%s=%s\n' "$key" "$(cat "$file")"
    done
done
